#! /bin/dash

while [ $# -gt 0 ]
do
    filelist=""
    case "$1" in
        dots)
            filelist=".coordinates .mpoprc .msmtprc .procmailrc .jnewsrc .urlview .eatrc .castgetrc"
            ;;
        dirs)
            filelist=".local .config .mutt .vim .mpd .themes .colors .fonts .icons .aria2 .irssi .pal .FontForge .ssh .w3m .elinks .lftp .ncmpcpp .audacity-data .audacity-files"
            ;;
        usenet)
            filelist=".slrn .slrnpull/slrnpull.conf"
            ;;
        mail)
            filelist=".maildir"
            ;;
        src)
            filelist="src/lang"
            ;;
        abs)
            filelist="src/abs"
            ;;
        doc)
            filelist="doc"
            ;;
        sys)
            filelist="/etc/rc.conf /etc/rc.local /usr/share/kbd/keymaps/extra.map /boot/grub/menu.lst /usr/local/bin/brightness /etc/pacman.conf $(ls /etc/udev/rules.d/* 2> /dev/null)"
            ;;
    esac
    if [ -n "$filelist" ] ; then
        tar -cvz -C ~ -f "${1}.tgz" $filelist
    fi
    shift
done
