#! /bin/dash

target=$(which "$@" 2> /dev/null)

if [ $? -eq 0 ]
then
    editor "$target"
else
    results="$(find -L "$XDG_BIN_DIR" -maxdepth 1 -type f -iname "*$@*" -print0 | xargs -0)"
    if [ -n "$results" ]; then
        editor $results
    fi
fi
