#! /bin/sh

select task in network user sound programs home
do
    echo $task
    case $task in
        network)
            # as root
            echo "ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=wheel" > /etc/wpa_supplicant.conf
            read -p "SSID? " SSID
            read -p "PASS? "  PASS
            wpa_passphrase "$SSID" "$PASS" >> /etc/wpa_supplicant.conf
            wpa_supplicant -B -Dwext -i wlan0 -c /etc/wpa_supplicant.conf
            dhcpcd wlan0
            pacman -S sudo netcfg wpa_actiond dhclient
            ;;
        user)
            # as root
            pacman -Syu
            useradd -m -g users -G audio,lp,optical,storage,video,wheel,games,power,scanner,log -s /bin/bash ice
            ;;
        sound)
            sudo pacman -S alsa-utils
            alsamixer
            speaker-test -c 2
            sudo alsactl store
            ;;
        programs)
            sudo pacman -S linux-docs
            sudo pacman -S bash-completion dash gdb
            sudo pacman -S curl yajl perl inetutils openssh openssl pkgfile
            sudo pacman -S git mercurial subversion cvs bzr
            sudo pacman -S zip unzip unrar
            sudo pacman -S pm-utils vim mutt msmtp ed
            sudo pacman -S rlwrap w3m elinks tmux duff ack surfraw dictd bc
            sudo pacman -S xorg-server xorg-xinit xorg-utils xorg-server-utils xorg-docs
            sudo pacman -S xorg-xmessage xorg-xclock xorg-xcalc xorg-xeyes
            sudo pacman -S terminus-font rxvt-unicode xscreensaver zenity gtk-engine-murrine
            sudo pacman -S scrot mplayer2 ffmpeg
            sudo pacman -S mpd mpc
            sudo pacman -S xclip xsel xdotool flashplugin
            sudo pacman -S gimp inkscape audacity
            sudo pacman -S cups gutenprint
            sudo pacman -S cdrkit gphoto2 dcraw
            sudo pacman -S lirc lirc-utils
            sudo pacman -S mac cuetools shntool libplist
            sudo pacman -S lsof strace words
            sudo pacman -S gnuplot gtk
            sudo pacman -S p7zip tk id3v2
            sudo pacman -S jd7-openjdk icedtea-web-java7 apache-ant
            sudo pacman -S apache php php-apache mysql
            sudo pacman -S abiword gnumeric sdlmame libreoffice-impress
            sudo pacman -S hfsprogs dosfstools
            sudo pacman -S libxcb xcb-proto xcb-util xcb-util-wm xcb-util-keysyms xcb-util-image
            sudo pacman -S fortune-mod figlet cowsay extundelete
            owl install sxhkd-git bspwm-git ewmhstatus-git backlight-git sres-git xlsw-git
            owl install python-colormath-git
            owl install urxvt-autocomplete-all-the-things-git
            owl install cower-git sxiv-git dwb-hg dmenu-q-xywh-xft-git
            owl install detox duff dictd-jargon dictd-wn stderred-git z-git
            owl install mutt-bare-git dzen2-bare-git
            owl install girara-common-git girara-gtk2-git zathura-git
            owl install zathura-pdf-poppler-git zathura-ps-git zathura-djvu-git
            owl install dfc-git compton-git youtube-dl-git
            owl install libuninameslist fontforge-bskv-git
            owl install ncmpcpp-git spdf-git jpdf-git
            owl install paps-bskv compface-bskv
            owl install grabc ppsei darcs-bin
            owl install ttf-anonymous-pro ttf-dejavu ttf-droid ttf-envy-code-r ttf-freefont ttf-junicode ttf-liberation ttf-linux-libertine ttf-ms-fonts
            owl install gnome-themes-standard faenza-icon-theme thunar
            ;;
        home)
            cd "$HOME"
            mkdir art doc incoming image audio video src tmp work misc public_html
            git clone git://github.com/baskerville/dotfiles.git .dotfiles
            git clone git://github.com/baskerville/bin.git .bin
            mkdir -p .sxiv/cache
            ;;
    esac
done
