#! /bin/dash

rulc -l > /dev/null
while [ $? eq 1 ] ; do
    sleep 0.1
    rulc -l > /dev/null
done

num=$(rulc -l | grep -m 1 -c class)
if [ $num -ne 1 ] ; then
    rulc -a 'class == "Gimp"' 'desktop = ^8, follow = on, floating = on'
    rulc -a 'class == "Inkscape"' 'desktop = ^7, follow = on, floating = on'
    rulc -a 'class == "fontforge"' 'desktop = ^6, follow = on, floating = on'
    rulc -a 'class == "fontforge" and (title == "Layers" or title == "Tools" or title == "Warnings")' 'focus = off'
    rulc -a 'class == "Gifview"' 'floating = on'
    rulc -a 'class == "Termite"' 'center = on'
fi
