#! /bin/dash

bspc set active_border_color        "#7D7F8A"
bspc set normal_border_color        "#3F3E3B"
bspc set inner_border_color         "#32312E"
bspc set outer_border_color         "#32312E"
bspc set presel_border_color        "#97AE71"
bspc set active_locked_border_color "#3289B0"
bspc set normal_locked_border_color "#3F3E3B"
bspc set urgent_border_color        "#DE928B"
