#! /bin/dash

if ! rulc -l > /dev/null ; then
    fork ruld
    while ! rulc -l > /dev/null ; do
        sleep 0.1
    done
fi
rules=$(rulc -l)
if [ -z "$rules" ] ; then
    rulc -a 'class == "Gimp"' 'desktop = ^8, follow = on, floating = on'
    rulc -a 'class == "Inkscape"' 'desktop = ^7, follow = on, floating = on'
    rulc -a 'class == "fontforge"' 'desktop = ^6, follow = on, floating = on'
    rulc -a 'class == "fontforge" and (title == "Layers" or title == "Tools" or title == "Warnings")' 'focus = off'
    rulc -a 'class == "Gifview"' 'floating = on'
    rulc -a 'class == "Termite"' 'center = on'
fi
