#! /bin/dash

usage() {
    printf "%s [-l LABEL] FILE ...\n" "$(basename "$0")"
    exit 0
}

[ $# -eq 0 ] && usage

label="noname"

while getopts "hl:" opt ; do
    case $opt in
        h)
            usage
            ;;
        l)
            label=$OPTARG
            ;;
    esac
done

shift $(($OPTIND - 1))

img=$(iso -l "$label" "$@")
[ -z "$img" ] && exit 1
isoinfo -J -l -i "$img"

printf "%s" "Ready to burn? [Y/n] "
read answer
[ -z "$answer" ] && answer="yes"

case "$answer" in
    y|Y|yes|Yes)
        wodim -v "$img"
        ;;
esac
