#! /bin/dash

if [ $# -eq 0 ] ; then
    printf "usage: %s [-f raw|arguments|indent] WIDTHxHEIGHT\n" "${0##*/}" >& 2
    exit 1
fi

output_format="raw"

while getopts "f:" opt ; do
    case $opt in
        f)
            output_format="$OPTARG"
            ;;
    esac
done

shift $((OPTIND - 1))

w=${@%x*}
h=${@#*x}

set - $(sres | awk -v w=$w -v h=$h '{match($0, /([0-9]+)x([0-9]+)/, groups); printf "%i %i\n", (groups[1] - w) / 2, (groups[2] - h) / 3;}')

xoffset=$1
yoffset=$2

case "$output_format" in
    arguments)
        printf "\055x %i \055y %i\n" "$xoffset" "$yoffset"
        ;;
    indent)
        printf "+%i+%i\n" "$xoffset" "$yoffset"
        ;;
    raw)
        printf "%i %i\n" "$xoffset" "$yoffset"
        ;;
    *)
        printf "unknown output format: '%s'\n" "$output_format" >& 2
        exit 1
esac
