#! /bin/bash

if [ $# -eq 0 ] ; then
    printf "usage: %s [-t geometrical|optical] WIDTHxHEIGHT\n" "${0##*/}" >& 2
    exit 1
fi

centering_type="geometrical"
k=2

while getopts "t:" opt ; do
    case $opt in
        t)
            centering_type="$OPTARG"
            ;;
    esac
done

shift $(($OPTIND - 1))

w=${@%x*}
h=${@#*x}

case "$centering_type" in
    geometrical)
        k=2
        ;;
    optical)
        k=3
        ;;
    *)
        printf "unknown centering type: '%s'\n" "$centering_type" >& 2
        exit 1
esac

xdpyinfo | awk -v w=$w -v h=$h -v k=$k 'BEGIN {IGNORECASE=1} /dimensions:/ {match($0, /[^0-9]+([0-9]+)x([0-9]+) pixels/, groups); printf "%i %i\n", (groups[1] - w) / 2, (groups[2] - h) / k;}'
