#! /bin/dash

bbcodes=$(mktemp)
tmpout=$(mktemp)

while [ $# -gt 0 ] ; do
    if [ -t 1 ] ; then
        printf '%s \033[1;36m%s\033[0m\n' "Chomping" "$1"
    else
        echo "Chomping $1"
    fi
    curl -# -F "file1=@$1" http://ompldr.org/upload -o "$tmpout"
    if [ $? -eq 0 ] ; then
        awk '/BBCode:/ { gsub(/<[^<]*?\/?>/, ""); $1=$1; sub(/^[^:]*:/, ""); print }' "$tmpout" >> "$bbcodes"
        if [ -t 1 ] ; then
            awk '/Info:|File:|Thumbnail:|BBCode:/ { gsub(/<[^<]*?\/?>/, ""); $1=$1; sub(/^/, "\033[1;30m"); sub(/:/, "\033[0m: "); print }' "$tmpout"
        else
            awk '/Info:|File:|Thumbnail:|BBCode:/ { gsub(/<[^<]*?\/?>/, ""); $1=$1; sub(/:/, ": "); print }' "$tmpout"
        fi
    fi
    shift
done

if [ -s "$bbcodes" ] ; then
    cat "$bbcodes" | xsel -bi
fi

rm "$tmpout" "$bbcodes"
