#! /bin/dash

SLENDER_PATTERN='└┬┘'
THICK_PATTERN=' ━ '
WHEEL_INDEXES='1 3 2 6 4 5'

printc() {
    printf '  \033[%sm%s\033[0m' "$1" "$2"
}

printf '\n'

for index in $WHEEL_INDEXES ; do
    background=$((100 + index))
    foreground=$((30 + index))
    printc "$background;$foreground" "$THICK_PATTERN"
done

printf '\n\n'

for index in $WHEEL_INDEXES ; do
    background=$((40 + index))
    printc "$background;97" "$THICK_PATTERN"
done

printf '\n\n'

for index in $WHEEL_INDEXES ; do
    foreground=$((90 + index))
    printc "40;$foreground" "$THICK_PATTERN"
done

printf '\n\n'

for color in '40;39' '100;37' '40;37' '100;37' '40;97' '100;97' ; do
    printc "$color" "$THICK_PATTERN"
done

printf '\n\n'

for attribute in 1 0 ; do
    for index in $WHEEL_INDEXES ; do
        foreground=$((30 + index))
        printc "$attribute;$foreground" "$SLENDER_PATTERN"
    done
    printf '\n\n'
done

for foreground in 90 39 37 39 97 39 ; do
    printc "$foreground" "$SLENDER_PATTERN"
done

printf '\n\n'
