#! /bin/dash

SLENDER_PATTERN='└┬┘'
THICK_PATTERN=' ━ '

printc() {
    printf '  \033[%sm%s\033[0m' "$1" "$2"
}

printf '\n'

for background in $(seq 101 106) ; do
    foreground=$((background - 70))
    printc "$background;$foreground" "$THICK_PATTERN"
done

printf '\n\n'

for background in $(seq 41 46) ; do
    printc "$background;97" "$THICK_PATTERN"
done

printf '\n\n'

for foreground in $(seq 91 96) ; do
    printc "40;$foreground" "$THICK_PATTERN"
done

printf '\n\n'

for color in '40;39' '100;37' '40;37' '100;37' '40;97' '100;97' ; do
    printc "$color" "$THICK_PATTERN"
done

printf '\n\n'

for attribute in 1 0 ; do
    for foreground in $(seq 31 36) ; do
        printc "$attribute;$foreground" "$SLENDER_PATTERN"
    done
    printf '\n\n'
done

for foreground in 90 39 37 39 97 39 ; do
    printc "$foreground" "$SLENDER_PATTERN"
done

printf '\n\n'
