#! /bin/bash

ANSI_COLORS="$(xrdb -query | grep -Ei urxvt[.*]color[01-9] | sort -n -tr -k2 | cut -d: -f2 | tr -d '[:blank:]')"

echo "
   BLK      RED      GRN      YEL      BLU      MAG      CYN      WHT  "
for i in {0..7}; do printf '%b' "\e[0;3${i}m $(echo "$ANSI_COLORS" | sed -n $(($i+1))'p')\e[0m "; done;
echo
for i in {0..7}; do printf '%b' "\e[0;9${i}m $(echo "$ANSI_COLORS" | sed -n $(($i+9))'p')\e[0m "; done;
echo
echo
