#! /bin/dash

pattern='██'
range=$(seq 30 37)

printf "\n"

for fg_color in $range ; do
    printf " \033[%sm%s\033[0m" "$fg_color" "$pattern"
done

printf "\n"

for fg_color in $range ; do
    printf " \033[1;%sm%s\033[0m" "$fg_color" "$pattern"
done

printf "\n\n"
