#! /usr/bin/env python2
# -*- coding: utf-8 -*-

import sys, os
import random
from PIL import Image
from getopt import getopt
from colormath.color_objects import LCHabColor, RGBColor

min_lightness, max_lightness = (0, 100)
min_chroma, max_chroma = (0, 200)
min_hue, max_hue = (0, 360)
num_colors = 6

def usage():
    print '''
SYNOPSIS
    %s [options] FILENAME ...

OPTIONS
    -h, --help
        Show this message.

    -n, --num-colors NUM
        Generates NUM colors (default: %s).

    -L, --lightness-range MIN-MAX
        Discard colors outside of the given lightness range (default: %s).

    -C, --chroma-range MIN-MAX
        Discard colors outside of the given chroma range (default: %s).

    -H, --hue-range MIN-MAX
        Discard colors outside of the given hue range (default: %s).
''' % (os.path.basename(sys.argv[0]), num_colors, '%s-%s' % (min_lightness, max_lightness), '%s-%s' % (min_chroma, max_chroma), '%s-%s' % (min_hue, max_hue))
    sys.exit()

def make_palette(img):
    global num_colors, min_lightness, max_lightness, min_chroma, max_chroma, min_hue, max_hue

    palette = []

    random.seed()
    img = img.convert('RGB')
    data = list(img.getdata())

    while len(palette) < num_colors and len(data) > 0:
        randindex = random.randint(0, len(data) - 1)
        pixel = data.pop(randindex)

        if type(pixel) is int:
            pixel = [pixel, pixel, pixel]

        (red, green, blue) = pixel
        rgb_color = RGBColor(red, green, blue)
        lch_color = rgb_color.convert_to('lchab')
        L, C, H = lch_color.get_value_tuple()

        if (min_lightness <= L <= max_lightness
                and min_chroma <= C <= max_chroma
                and min_hue <= H <= max_hue):
            palette.append(rgb_color)
            print rgb_color.get_rgb_hex().upper()

def main():
    global num_colors, min_lightness, max_lightness, min_chroma, max_chroma, min_hue, max_hue

    opts, args = getopt(sys.argv[1:], 'hn:L:C:H:', ['help', 'num-colors=', 'lightness-range=', 'chroma-range=', 'hue-range='])

    if len(args) < 1:
        usage()

    for opt, val in opts:
        if opt in ('-h', '--help'):
            usage()
        elif opt in ('-n', '--num-colors'):
            num_colors = int(val)
        elif opt in ('-L', '--lightness-range'):
            min_lightness, max_lightness = map(int, val.split('-'))
        elif opt in ('-C', '--chroma-range'):
            min_chroma, max_chroma = map(int, val.split('-'))
        elif opt in ('-H', '--hue-range'):
            min_hue, max_hue = map(int, val.split('-'))

    for file_name in args:
        try:
            img = Image.open(file_name)
        except IOError:
            print >> sys.stderr, "could not open '%s'" % file_name
            sys.exit(1)
        make_palette(img)

if __name__ == '__main__':
    main()
