#! /bin/dash

pattern="██"

printf "\n"

for fg_color in $(seq 31 36) ; do
    printf " \033[%sm%s\033[0m" "$fg_color" "$pattern"
done

printf "\n"

for fg_color in $(seq 31 36) ; do
    printf " \033[1;%sm%s\033[0m" "$fg_color" "$pattern"
done

printf "\n\n"
