#! /bin/dash

while [ $# -ne 0 ]; do
    ext=${1##*.}
    flag=$(date +%Y%m%d_%H%M%S)
    tagged_name=${1%.*}_$flag.$ext

    [ "$ext" = "$1" ] && tagged_name=${1}_$flag

    [ -e "$tagged_name" ] || cp -r "$1" "$tagged_name" 

    shift
done
