#! /bin/dash

diana list > /dev/null 2>&1

if [ $? -eq 0 ]; then
    echo 'the daemon is already running' >&2
    exit 1
fi

hashes_file=$XDG_DATA_HOME/aria2hashes
backup_hashes=$XDG_DATA_HOME/aria2hashes.bak

if [ ! -e "$hashes_file" ]
then
    if [ -e "$backup_hashes" ]; then
        mv "$backup_hashes" "$hashes_file"
    fi
fi

tmp_file=$(mktemp)

sort -u "$hashes_file" > "$tmp_file"
cp "$tmp_file" "$hashes_file"
rm "$tmp_file"

aria2c -D --enable-rpc -j 16 -d "$XDG_TMP_DIR" -l ~/.aria2/log --on-bt-download-complete "$XDG_BIN_DIR/aria2_bt_download_complete_hook"

for line in $(cat $hashes_file); do
    rhsh=${line%:*}
    sel=${line#*:}
    hsh=${rhsh#_}

    for tor in "$XDG_TMP_DIR"/*.torrent; do
        match=$(aria2c -S "$tor" | grep -m 1 "$hsh")
        if [ -n "$match" ]; then
            echo "$tor"
            gid=$(diana --select-file="$sel" add "$tor")
            [ $? -ne 0 ] && exit 1
            case $rhsh in
                _*)
                    diana pause $gid;;
            esac
        fi
    done
done

mv "$hashes_file" "$backup_hashes"
