#! /bin/dash

. dbatt_colors

gauge_fg=$ACTIVE_FG
gauge_bg=$ACTIVE_BG
bar_fg=$TEXT_FG
bar_bg=$TEXT_BG
gauge_label="BAT"

case "$@" in
    status)
        :
        ;;
esac

dgauge -l "$gauge_label" -f "$bar_fg" -b "$bar_bg" -F "$gauge_fg" -B "$gauge_bg" $(acpi -b | grep -o '[0-9]\+%' | tr -cd '[0-9]') 100
