#! /bin/dash

if [ $# -eq 0 ] ; then
    printf "%s\n" "no action given" >&2
    exit 1
fi

. dbright_colors

gauge_fg=$ACTIVE_FG
gauge_bg=$ACTIVE_BG
bar_fg=$TEXT_FG
bar_bg=$TEXT_BG
gauge_label="BRI"

sudo brightness "$@"

dgauge -l "$gauge_label" -f "$bar_fg" -b "$bar_bg" -F "$gauge_fg" -B "$gauge_bg" $(sudo brightness info)
