#! /bin/dash

. dmenu_colors

FONT='sans-serif:pixelsize=11'

dmenu -i -h "$PANEL_HEIGHT" -fn "$FONT" -nb "$NORMAL_BACKGROUND" -nf "$NORMAL_FOREGROUND" -sb "$SELECTED_BACKGROUND" -sf "$SELECTED_FOREGROUND"
