#! /bin/dash

if [ $# -eq 0 ] ; then
    printf "%s\n" "no action given" >&2
    exit 1
fi

. dvol_colors

AUDIO_INFO_CMD="amixer get Master"
AUDIO_TOGGLE_CMD="amixer -q set Master toggle"
AUDIO_RAISE_CMD="amixer -q set Master 1+"
AUDIO_LOWER_CMD="amixer -q set Master 1-"
AUDIO_RAISE_STRONG_CMD="amixer -q set Master 1%+"
AUDIO_LOWER_STRONG_CMD="amixer -q set Master 1%-"
AUDIO_MIN_CMD="amixer -q set Master 0%"
AUDIO_MAX_CMD="amixer -q set Master 100%"

TMP_STDOUT="/tmp/dvol_stdout"

gauge_fg=$ACTIVE_FG
gauge_bg=$ACTIVE_BG
bar_fg=$TEXT_FG
bar_bg=$TEXT_BG
gauge_label="VOL"
muted=0

case "$@" in
    status)
        :
        ;;
    toggle)
        $AUDIO_TOGGLE_CMD
        ;;
    raise)
        $AUDIO_RAISE_CMD
        ;;
    lower)
        $AUDIO_LOWER_CMD
        ;;
    strong_raise)
        $AUDIO_RAISE_STRONG_CMD
        ;;
    strong_lower)
        $AUDIO_LOWER_STRONG_CMD
        ;;
    min)
        $AUDIO_MIN_CMD
        ;;
    max)
        $AUDIO_MAX_CMD
        ;;
    *)
        printf "unknown action: '%s'\n" "$@" >&2
        exit 1
        ;;
esac

$AUDIO_INFO_CMD > "$TMP_STDOUT"
gauge_cur=$(awk '/%/ { sub(/^[^0-9]*/, ""); print $1; }' "$TMP_STDOUT")
gauge_max=$(awk -F ' *- *' 'BEGIN {IGNORECASE=1} /limits:/ {print $2}' "$TMP_STDOUT")

grep -i '\[on\]' "$TMP_STDOUT" > /dev/null 2>&1 || muted=1

if [ "$muted" -eq 1 ] ; then
    gauge_fg=$MUTED_FG
    gauge_bg=$MUTED_BG
    gauge_label="MUT"
fi

dgauge -l "$gauge_label" -f "$bar_fg" -b "$bar_bg" -F "$gauge_fg" -B "$gauge_bg" "$gauge_cur" "$gauge_max"
