#! /bin/dash

width_height=`xwininfo -root | grep -m 1 '\-geometry' | grep -oE '[0-9]+x[0-9]+'`

width=${width_height%x*}
height=${width_height#*x}
bar_width=$(( $width / 3 ))
bar_height=$(( $height / 5 ))
left_shift=$(( ($width - $bar_width) / 2 ))
top_shift=$(( $height / 3 ))
fn='-*-terminus-medium-r-normal-*-20-*-*-*-*-*-iso10646-*'
bg='#171513'
fg='#929292'

dzen2 -fn "$fn" -bg "$bg" -fg "$fg" -x $left_shift -y $top_shift -w $bar_width -h $bar_height -p 5
