#! /bin/dash

CHUNK_LENGTH=8
colors=$(cat | grep -o 'color[0-9]\+' | tr -d '[a-z]')
only_block=0
only_index=0

[ $# -gt 0 ] && [ $@ = '-b' ] && only_block=1
[ $# -gt 0 ] && [ $@ = '-i' ] && only_index=1

counter=0
block='■'

printf '\n'

for i in $colors
do
    pattern=''
    [ $only_index -eq 0 ] && pattern="${block}${pattern}"
    [ $only_block -eq 0 ] && pattern="${pattern}$(printf '%03d' $i)"
    printf " \033[38;5;${i}m%b" "$pattern"
    counter=$((counter+1))
    [ $((counter%CHUNK_LENGTH)) -eq 0 ] && printf '\n'
done

printf '\n'
