#! /bin/dash

while [ $# -gt 0 ] ; do
    prg=$1
    case "$prg" in
        dwb | dwb_restore)
            CMD=dwb
            [ "$prg" = "dwb_restore" ] && CMD="$CMD -rf default"
            wid=$(lswi | grep Dwb | sed 's/.*(\(0x[0-9A-F]\+\))$/\1/')
            if [ -n "$wid" ] ; then
                xdotool windowactivate "$wid"
            else
                pgrep -x dwb > /dev/null || $CMD
            fi
            ;;
        mutt | slrn | htop | bspwm_config | sxhkd_config | ncmpcpp)
            CMD=$prg
            case "$prg" in
                mutt)
                    CMD=m
                    ;;
                slrn)
                    CMD=ng
                    ;;
                bspwm_config)
                    CMD="editor ${XDG_CONFIG_HOME}/bspwm/autostart"
                    ;;
                sxhkd_config)
                    CMD="editor ${XDG_DOTFILES_DIR}/sxhkdrc"
                    ;;
            esac
            case "$prg" in
                mutt | slrn | ncmpcpp | htop)
                    pgrep -x "$prg" > /dev/null && CMD=""
                    ;;
            esac
            xdotool search --classname "$prg" windowactivate || urxvtc -title "$prg" -name "$prg" -e $CMD
            ;;
        *)
            xdotool search --classname "$prg" windowactivate || urxvtc -name "$prg" -e editor "${XDG_DATA_HOME}/$prg"
            ;;
    esac
    shift
done
