#! /bin/dash

while [ $# -gt 0 ] ; do
    prg=$1
    case "$prg" in
        dwb | dwb_restore)
            CMD=dwb
            [ "$prg" = "dwb_restore" ] && CMD="$CMD -rf default"
            if ! bspc query -W | xargs xdo activate -N Dwb ; then
                pgrep -x dwb > /dev/null || $CMD
            fi
            ;;
        mutt | top | bspwm_config | sxhkd_config | ncmpcpp)
            CMD=$prg
            case "$prg" in
                mutt)
                    CMD=m
                    ;;
                bspwm_config)
                    CMD="editor ${XDG_CONFIG_HOME}/bspwm/autostart"
                    ;;
                sxhkd_config)
                    CMD="editor ${XDG_DOTFILES_DIR}/sxhkdrc"
                    ;;
            esac
            case "$prg" in
                mutt | ncmpcpp | top)
                    pgrep -x "$prg" > /dev/null && CMD=""
                    ;;
            esac
            xdo activate -n "$prg" || urxvtc -title "$prg" -name "$prg" -e $CMD
            ;;
        *)
            xdo activate -n "$prg" || urxvtc -name "$prg" -e editor "${XDG_DATA_HOME}/$prg"
            ;;
    esac
    shift
done
