#! /bin/dash

set -e
base=$(basename "$1")
ssh_url=$(printf "%s" "$1" | sed 's!.*://\([^/]\+\)/\([^/]\+\)/\([^/]\+\)!git@\1:\2/\3.git!')
mkdir "$base"
cd "$base"
git init
git remote add origin "$ssh_url"
