#! /bin/dash

SAFETY_DELAY=9

timeout=$((DPMS_STANDBY - SAFETY_DELAY))

if [ $timeout -lt 1 ] ; then
    printf '%s' "timeout can't be negative" >&2
    exit 1
fi

while true ; do
    sleep $timeout
    awid=$(xprop _NET_ACTIVE_WINDOW -root 2> /dev/null | grep -io '0x[0-9a-f]\+')
    # date_stamp=$(date "+%H:%M")
    if [ $? -eq 0 ] ; then
        wstate=$(xprop _NET_WM_STATE -id "$awid" 2> /dev/null)
        if [ $? -eq 0 ] ; then
            case "$wstate" in
                *_NET_WM_STATE_FULLSCREEN)
                    xset -dpms
                    # printf "%s dpms deactivated (fullscreen)\n" "$date_stamp" >> ~/.happy_fs.log
                    ;;
                *)
                    xset +dpms
                    # printf "%s dpms activated (wrong state)\n" "$date_stamp" >> ~/.happy_fs.log
                    ;;
            esac
        else
            xset +dpms
            # printf "%s dpms activated (can't get state)\n" "$date_stamp" >> ~/.happy_fs.log
        fi
    else
        xset +dpms
        # printf "%s dpms activated (no active window)\n" "$date_stamp" >> ~/.happy_fs.log
    fi
done
