#! /bin/dash

SAFETY_DELAY=9

timeout=$((DPMS_STANDBY - SAFETY_DELAY))

if [ $timeout -lt 1 ] ; then
    printf '%s' "timeout can't be negative" >&2
    exit 1
fi

while true ; do
    sleep $timeout
    awid=$(xprop _NET_ACTIVE_WINDOW -root 2> /dev/null | grep -io '0x[0-9a-f]\+')
    if [ $? -eq 0 ] ; then
        wstate=$(xprop _NET_WM_STATE -id "$awid")
        case "$wstate" in
            *_NET_WM_STATE_FULLSCREEN)
                xset -dpms
                ;;
            *)
                xset +dpms
                ;;
        esac
    else
        xset +dpms
    fi
done
