#! /bin/dash

SAFETY_DELAY=9

timeout=$((DPMS_STANDBY - SAFETY_DELAY))

if [ $timeout -lt 1 ] ; then
    printf '%s' "timeout can't be negative" >&2
    exit 1
fi

while true ; do
    sleep $timeout
    awid=$(xdotool getactivewindow 2>/dev/null)
    if [ $? -eq 0 ] ; then
        wstate=$(xprop -id "$awid" _NET_WM_STATE)
        current_date=$(date "+%Y/%m/%d %H:%M:%S")
        case "$wstate" in
            *_NET_WM_STATE_FULLSCREEN)
                xset -dpms
                echo "$current_date dmps disabled" >> ~/.happy_fs.log
                ;;
            *)
                xset +dpms
                echo "$current_date dmps enabled" >> ~/.happy_fs.log
                ;;
        esac
    fi
done
