#! /bin/dash

hc set frame_bg_normal_color      '#1F1E1B'
hc set frame_bg_active_color      '#1F1E1B'
hc set frame_border_normal_color  '#3F3E3B'
hc set frame_border_active_color  '#7D7F8A'
hc set frame_border_inner_color   '#2B2B28'
hc set window_border_normal_color '#3F3E3B'
hc set window_border_active_color '#7D7F8A'
hc set window_border_inner_color  '#32312E'
