#! /bin/dash

hc set frame_bg_normal_color      '#FFFFFF'
hc set frame_bg_active_color      '#FFFFFF'
hc set frame_border_normal_color  '#EAE5D6'
hc set frame_border_active_color  '#969BA9'
hc set window_border_normal_color '#EAE5D6'
hc set window_border_active_color '#969BA9'
