#! /bin/dash

hc set frame_bg_normal_color      '#FAF0E6'
hc set frame_bg_active_color      '#FFF9EE'
hc set frame_border_normal_color  '#FAF0E6'
hc set frame_border_active_color  '#FFF9EE'
hc set window_border_normal_color '#E7DFD5'
hc set window_border_active_color '#8F98A1'
