#! /usr/bin/env python3

import sys, re
from colormath.color_objects import RGBColor

palette = []
ILLUMINANT='d65'
args = sys.argv[1:]

if len(args) > 0:
    palette.extend(args)
else:
    for line in sys.stdin:
        color_codes = re.findall('#[0-9A-F]{6}', line, flags=re.IGNORECASE)
        palette.extend(color_codes)

if len(palette) < 1:
    print('no color found', file=sys.stderr)
    sys.exit(1)

for c in palette:
    color = RGBColor()
    color.set_from_rgb_hex(c)
    lab = color.convert_to('lab', target_illuminant=ILLUMINANT)
    print('%f %f %f' % (lab.lab_l, lab.lab_a, lab.lab_b))
