#! /bin/dash

_incg() {
    local names="$(grep '^#include *"[^"]\+"' "$1" 2> /dev/null | sed 's/[^"]\+"\([^"]\+\)".*/\1/')"
    if [ -z "$names" ] ; then
        case "$1" in
            *.h)
                printf "%s\n" "$1"
                ;;
        esac
    else
        for nm in $names ; do
            _incg "$nm"
        done
    fi
}

suffix=.o

while getopts 'hs:' opt ; do
    case $opt in
        s)
            suffix=$OPTARG
            ;;
        h)
            printf "%s [-h|-s SUFFIX] CSOURCE ...\n" "${0##*/}"
            ;;
    esac
done

shift $((OPTIND - 1))

while [ $# -gt 0 ] ; do
    printf "%s: %s" "${1%.*}$suffix" "$1"
    for nm in $(_incg "$1" | sort -u) ; do
        printf " %s" "$nm"
    done
    printf "\n"
    shift
done
