#! /bin/dash

list_type=${1:-rating}
tmp_out=$(mktemp --suffix .png)

curl -s "https://kuler-api.adobe.com/feeds/rss/get.cfm?timeSpan=0&listType=$list_type" | grep -o '\([0-9A-F]\{6\}\(, \)\?\)\{5\}' | sed 's/, / /g;s/\([0-9A-F]\{6\}\)/#\1/g' | hex2img -g 3 -n 5 "$tmp_out"

image_viewer "$tmp_out"
