#! /bin/dash

while [ $# -gt 0 ] ; do
    link=$1
    parent=$(dirname "$link")
    printf 'cd "%s" && ln -s "%s" "%s"\n' "$(readlink -nf "$parent" | sed "s:$HOME:\$HOME:")" "$(readlink -n "$link")" "$(basename "$link")"
    shift
done
