#! /bin/dash

while [ $# -ne 0 ] ; do
    fla_dir=$(mktemp -d -t fla.XXX)
    unzip -d $fla_dir $1 LIBRARY/**.xml > /dev/null 2>&1
    find $fla_dir -type f -exec get_flash_symbol_names {} \;
    rm -r $fla_dir
    shift
done
