#! /bin/dash

ext='jpg'
side=80
quality=75
gravity='Center'
pixel=1
filter='Cubic'

while getopts 's:e:p:q:g:f:' opt ; do
    case $opt in
        s)
            side=$OPTARG
            ;;
        e)
            ext=$OPTARG
            ;;
        p)
            pixel=$OPTARG
            ;;
        q)
            quality=$OPTARG
            ;;
        g)
            gravity=$OPTARG
            ;;
        f)
            filter=$OPTARG
            ;;
    esac
done

shift $(($OPTIND - 1))

if [ $# -lt 1 ] ; then
    printf "usage: %s [-s SIDE|-e EXT|-p PIXEL|-q QUALITY|-g GRAVITY|-f FILTER] FILE ...\n" "${0##*/}"
    exit 1
fi

shrink=$(((100 * pixel) / side))
grow=$(((100 * side) / pixel))

while [ $# -gt 0 ] ; do
    imagepath=$1
    imagedir=$(dirname "$imagepath")
    imagebase=$(basename "$imagepath")
    imagebase=${imagebase%.*}
    thumbdir="$imagedir/thumbnails"
    mkdir -p "$thumbdir"
    thumbpath="$thumbdir/tn_$imagebase.$ext"
    convert -filter "$filter" -resize ${side}x${side}^ -gravity $gravity -extent ${side}x${side} -quality $quality -interlace Line "$imagepath" "$thumbpath"
    if [ $pixel -gt 1 ] ; then
        mogrify -filter "$filter" -colorspace LAB -resize ${shrink}% -colorspace sRGB -auto-level -scale ${grow}% "$thumbpath"
    fi
    shift
done
