#! /bin/dash

ext='jpg'
side=80
quality=75
gravity='North'
pixel=0

while getopts 's:e:p:q:g:' opt ; do
    case $opt in
        s)
            side=$OPTARG
            ;;
        e)
            ext=$OPTARG
            ;;
        p)
            pixel=$OPTARG
            ;;
        q)
            quality=$OPTARG
            ;;
        g)
            gravity=$OPTARG
            ;;
    esac
done

shift $(($OPTIND - 1))

if [ $# -lt 1 ] ; then
    printf "usage: %s [-s SIDE|-e EXT|-p PIXEL|-q QUALITY|-g GRAVITY] FILE ...\n" "${0##*/}"
    exit 1
fi

small=$((side / 4))

while [ $# -gt 0 ] ; do
    imagepath=$1
    imagedir=$(dirname "$imagepath")
    imagebase=$(basename "$imagepath")
    imagebase=${imagebase%.*}
    thumbdir="$imagedir/thumbnails"
    mkdir -p "$thumbdir"
    thumbpath="$thumbdir/tn_$imagebase.$ext"
    convert -resize ${side}x${side}^ -gravity $gravity -extent ${side}x${side} -quality $quality -interlace Line "$imagepath" "$thumbpath"
    if [ $pixel -gt 0 ] ; then
        shrink=$((side / pixel))
        grow=$((10000 / shrink))
        mogrify -filter Catrom -resize ${shrink}% -scale ${grow}% "$thumbpath"
    fi
    shift
done
