#! /usr/bin/python

import sys, re
from urllib.parse import urljoin, urlparse
from getopt import getopt

base = None
tag = 'href'

def format_links(line):
    global base, tag
    hyper_refs = re.findall('(?<={}=")[^"]+'.format(tag), line, flags = re.I)
    for href in hyper_refs:
        if base:
            print(urljoin(base, href))
        else:
            print(href)

def main():
    global base, tag
    opts, args = getopt(sys.argv[1:], 'b:t:', ['base=', 'tag='])

    for opt, val in opts:
        if opt in ('-b', '--base'):
            base = val
        if opt in ('-t', '--tag'):
            tag = val

    if len(args) > 0:
        for filename in args:
            fd = open(filename, 'r', errors='ignore')
            for line in fd.readlines():
                format_links(line)
            fd.close()
    else:
        for line in sys.stdin:
            format_links(line)

if __name__ == '__main__':
    main()
