#! /bin/dash

if [ $(pgrep -cx panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi


trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

. panel_colors

if [ ! -p "$PANEL_FIFO" ] ; then
    [ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
    mkfifo "$PANEL_FIFO"
fi

bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &
clock -s -i 5 -f 'C%A %H:%M' > "$PANEL_FIFO" &
essid -s -i 3 -f 'N%s' > "$PANEL_FIFO" &
if battery > /dev/null 2>&1 ; then
    battery -s -i 11 -f 'B%s %i' > "$PANEL_FIFO" &
fi
volume status &
bright status &

cat "$PANEL_FIFO" | panel_dzen2 -f "$PANEL_FONT_FAMILY" -s "$PANEL_FONT_SIZE" -F "$PANEL_ICONS_FONT_FAMILY" -S "$PANEL_ICONS_FONT_SIZE" | dzen2 -h $PANEL_HEIGHT -dock -ta l -title-name panel -fn "${PANEL_FONT_FAMILY}:pixelsize=${PANEL_FONT_SIZE}" -fg "$COLOR_FOREGROUND" -bg "$COLOR_BACKGROUND" &

wait
