#! /bin/dash
# $1 is the input file
# $2 is the first page of the range to extract
# $3 is the last page of the range to extract
# output file will be named "inputfile_pXX-pYY.pdf"

gs -sDEVICE=pdfwrite -dNOPAUSE -dBATCH -dSAFER \
   -dFirstPage=${2} \
   -dLastPage=${3} \
   -sOutputFile="${1%.pdf}_p${2}-${3}.pdf" \
   "${1}"
