#! /bin/dash

while [ $# -gt 0 ] ; do
    results=$(eat find $1 | sort | cut -d' ' -f 2- | tr '\n' ':')
    IFS=':'
    for r in $results ; do
        IFS=' '
        printf '[url=%s][img]%s[/img][/url]\n' "$(eat url $r)" "$(eat thumb $r)"
    done
    shift
done
