#! /bin/dash

while [ $# -gt 0 ] ; do
    case "$1" in
        dwb | dwb_restore)
            CMD=dwb
            [ "$1" = "dwb_restore" ] && CMD="$CMD -rf default"
            wid=$(lswi --class dwb | head -1 | sed 's/.*(\([0-9]\+\))$/\1/')
            if [ -n "$wid" ] ; then
                xdotool windowactivate "$wid"
            else
                pgrep -x dwb > /dev/null || $CMD
            fi
            ;;
        mutt | slrn | htop | xlog | hlconf | ncmpcpp)
            CMD=$1
            case "$1" in
                mutt)
                    CMD=m
                    ;;
                slrn)
                    CMD=ng
                    ;;
                xlog)
                    CMD="editor $HOME/.Xlog"
                    ;;
                hlconf)
                    CMD="editor ${XDG_CONFIG_HOME}/herbstluftwm/autostart"
                    ;;
            esac
            xdotool search --classname "$1" windowactivate || urxvtc -title "$1" -name "$1" -e $CMD
            ;;
        *)
            xdotool search --classname "$1" windowactivate || urxvtc -name "$1" -e editor "${XDG_DATA_HOME}/$1"
            ;;
    esac
    shift
done
