#! /bin/dash

if ! [ -e "$XDG_TRASH_DIR" ] ; then
    printf "%s\n" "The 'XDG_TRASH_DIR' environment variable is not defined." >&2
    exit 1
fi

for raw in *.CR2; do
    base=${raw%.*}
    good=$(ls $base.* | grep -v $raw)
    if [ -z "$good" ]; then
        echo "trashing $raw"
        mv -t "$XDG_TRASH_DIR" "$raw"
    fi
done
