#! /bin/dash

[ $# -lt 2 ] && exit 1

conf=$1
bgtype=$2

name=$(basename "$conf")
current=$(readlink -nse "$conf")
dir=$(dirname "$current")

[ ! -e "$dir/${name}-${bgtype}" ] && exit 1

cd "$dir"
ln -sf "${name}-${bgtype}" "$name"
