#! /bin/dash

[ $# -lt 1 ] && exit 1

theme_name=$(basename "$@")

cd "$XDG_COLORS_DIR"

ln -sf "$theme_name" current
xrdb -merge current

ln -sf "redef-$theme_name" redef-current
for vt in $(find /dev/pts/ -maxdepth 1 -type c -group tty) ; do
    [ -w "$vt" ] && ./redef-current > "$vt"
done
