#! /bin/dash

if [ $# -eq 0 ] ; then
    printf "%s\n" "no argument given" >&2
    exit 1
fi

if [ -e "$@" ] ; then
    cp "$@" "$WALLPAPER"
    reloadwallpaper
else
    printf "%s: '%s'\n" "file not found" "$@" >&2
    exit 1
fi
