#! /usr/bin/env python3

import sys
import re
from os.path import basename

MIN_VAL = 232
MAX_VAL = 255

args = sys.argv[1:]

if len(args) != 1:
    print('wrong number of arguments', file = sys.stderr)
    print('syntax: {} [+-]VALUE'.format(basename(sys.argv[0])))
    sys.exit(1)

delta = int(args[0])

def shift_value(match_obj):
    global delta
    prefix = match_obj.group(1)
    color = int(match_obj.group(2))
    dc = color
    if dc >= MIN_VAL and dc <= MAX_VAL:
        dc = color + delta
        if dc > MAX_VAL:
            dc = MAX_VAL
        if dc < MIN_VAL:
            dc = MIN_VAL
    return '{}{}'.format(prefix, dc)

for line in sys.stdin:
    sline = re.sub('(cterm[fb]g=|[34]8;5;|#define\s+\w+\s+)(\d+)', shift_value, line)
    print(sline, end='')
