#! /bin/dash

classname=$1
filepath=$2

xface_pth=${filepath:-/tmp/xface}
xbm_img=$(mktemp)
tmp_out=$(mktemp)

uncompface -X "$xface_pth" "$xbm_img"
size=$(grep -m 1 -o '[0-9]\+' "$xbm_img")
size=$((size + 7))

wid=$(xdotool search --classname $classname)
[ $? -ne 0 ] && exit 1
xwininfo -id "$wid" > "$tmp_out"
top_x=$(awk -F ' *: *' '/Absolute upper-left X/ {print $2}' "$tmp_out")
top_y=$(awk -F ' *: *' '/Absolute upper-left Y/ {print $2}' "$tmp_out")
width=$(awk -F ' *: *' '/Width/ {print $2}' "$tmp_out")
height=$(awk -F ' *: *' '/Height/ {print $2}' "$tmp_out")
bw=$(awk -F ' *: *' '/Border width/ {print $2}' "$tmp_out")
pos_x=$((top_x + width - size + bw))
pos_y=$((top_y + height - size + bw))

printf "%s\n" "^i($xbm_img)" | dzen2 -x $pos_x -y $pos_y -w $size -h $size -p 2 &

rm "$tmp_out"
