#! /bin/dash

name=$(basename "$1")
size=$(du -h "$1" | cut -f 1)
geom=$(identify -format '%wx%h' "$1[0]")

# tags=$(exiv2 -q pr -pi "$1" | awk '$1~"Keywords" { printf("%s,", $4); }')
# tags=${tags:+|}${tags%,}

printf "%s %s %s\n" "$geom" "$size" "$name"
