#! /bin/dash

pgrep -x urxvtd > /dev/null || urxvtd -q -o -f

if [ $# -eq 0 ] ; then
    recpth=$(cat "$HOME/.z" | awk -F '|' '{print $3, $1}' | sort -n | tail -n 1 | sed 's:^[^/]\+::')
    [ -z "$recpth" ] && recpth=$HOME
    urxvtc -cd "$recpth"
else
    urxvtc $@
fi
