#! /bin/dash

while [ $# -gt 0 ] ; do
    filepth=$1
    base=${filepth%.*}
    paps --header --font "Courier New 11" --header-font "DejaVu Sans 9" --header-date-format "%Y %m %d %H:%M" "$filepth" > "${base}.ps"
    shift
done

