#! /bin/dash

[ ! -e "$PANEL_PGRP" ] && exit 1

top_padding=$(bspc get top_padding)

if [ $top_padding -eq $PANEL_HEIGHT ] ; then
    top_padding=0
    action=windowunmap
else
    top_padding=$PANEL_HEIGHT
    action=windowmap
fi

xdotool search --all --pid $(pgrep -g $(cat "$PANEL_PGRP") -x dzen2) --name panel $action
bspc set top_padding $top_padding
