#! /bin/dash

current=$(readlink -nse "$XDG_COLORS_DIR/current")
if [ $? -eq 1 ] ; then
    echo "can't find the current color theme" >&2
    exit 1
fi
base=$(basename "$current")
name=${base%-*}
bgtype=${base##*-}

if [ $# -gt 0 ] ; then
    bgtype=$1
else
    case "$bgtype" in
        dark)
            bgtype=light
            ;;
        light)
            bgtype=dark
            ;;
    esac
fi


setthm "${name}-${bgtype}"

# setconfbg "$XDG_DOTFILES_DIR/neaprc" $bgtype
# setconfbg "$XDG_DOTFILES_DIR/tint2rc" $bgtype
setconfbg "$XDG_DOTFILES_DIR/override.css" $bgtype
setconfbg "$XDG_BIN_DIR/dmenu_launch" $bgtype
setconfbg "$XDG_BIN_DIR/dmenu_select" $bgtype

setconfbg "$XDG_BIN_DIR/hc_colors" $bgtype
setconfbg "$XDG_BIN_DIR/bspwm_colors" $bgtype
setconfbg "$XDG_BIN_DIR/setrootbg" $bgtype
setconfbg "$XDG_BIN_DIR/show_xface_colors" $bgtype
setconfbg "$XDG_BIN_DIR/dvol_colors" $bgtype
setconfbg "$XDG_BIN_DIR/dbright_colors" $bgtype
setconfbg "$XDG_BIN_DIR/dbatt_colors" $bgtype
setconfbg "$XDG_BIN_DIR/dnotify_colors" $bgtype

setconfbg "$XDG_DOTFILES_DIR/dzen2_Xresources" $bgtype
xrdb -merge "$XDG_DOTFILES_DIR/dzen2_Xresources"

setrootbg
hc_colors
reloadpanel
