#! /bin/dash

[ ! -e "$PANEL_LOCK" ] && exit 1

set -- $(bspc query -T | grep '#$' | cut -d ' ' -f 3 | tr ',' ' ')
top_padding=$1
shift

if [ $top_padding -eq $PANEL_HEIGHT ] ; then
    top_padding=0
    action=hide
else
    top_padding=$PANEL_HEIGHT
    action=show
fi

pgrp=$(ps -p $(pgrep -nx clock) -o pgrp= | tr -d ' ')
xdo $action -p $(pgrep -g $pgrp -x dzen2) -N dzen
bspc monitor -p $top_padding "$@"
