#! /bin/dash

current=$(readlink -nse "$XDG_COLORS_DIR/xresources")

if [ $? -eq 1 ] ; then
    echo "Can't find the current color theme" >&2
    exit 1
fi

base=$(basename "$current")
bgtype=${base##*-}

if [ $# -gt 0 ] ; then
    bgtype=$1
else
    case "$bgtype" in
        dark)
            bgtype=light
            ;;
        light)
            bgtype=dark
            ;;
    esac
fi

setconfbg "$XDG_COLORS_DIR/xresources" $bgtype
setconfbg "$XDG_COLORS_DIR/redef" $bgtype
setconfbg "$XDG_COLORS_DIR/redef_console" $bgtype

setconfbg "$XDG_DOTFILES_DIR/override.css" $bgtype
setconfbg "$XDG_DOTFILES_DIR/dzen2_xresources" $bgtype
setconfbg "$XDG_DOTFILES_DIR/termite_config" $bgtype
# setconfbg "$XDG_DOTFILES_DIR/themes/vim/raven.vim" $bgtype
# setconfbg "$XDG_DOTFILES_DIR/gtk2_gvim" $bgtype

setconfbg "$XDG_BIN_DIR/dmenu_colors" $bgtype
setconfbg "$XDG_BIN_DIR/bspwm_colors" $bgtype
setconfbg "$XDG_BIN_DIR/panel_colors" $bgtype
# setconfbg "$XDG_BIN_DIR/show_xface_colors" $bgtype
setconfbg "$XDG_BIN_DIR/dnotify_colors" $bgtype

setconfbg "$WALLPAPER" $bgtype
