#! /bin/dash

[ ! -e "$PANEL_LOCK" ] && exit 1

top_padding=$(bspc get top_padding)

if [ $top_padding -eq $PANEL_HEIGHT ] ; then
    top_padding=0
    action=windowunmap
else
    top_padding=$PANEL_HEIGHT
    action=windowmap
fi

pgrp=$(ps -p $(pgrep -nx clock) -o pgrp= | tr -d ' ')
xdotool search --all --pid $(pgrep -g $pgrp -x dzen2) --name panel $action
bspc set top_padding $top_padding
