#! /bin/dash

printf '\n'

for foreground in 31 32 33 34 35 36
do
    printf "\033[1;${foreground}m%b\033[0m" '█'
done

printf '\n'

for foreground in 31 32 33 34 35 36
do
    printf "\033[${foreground}m%b\033[0m" '█'
done

printf '\n\n'
