#! /usr/bin/env python3

import unicodedata
import sys

eol = '\n'
if not sys.stdout.isatty():
    eol = '  '

for line in sys.stdin:
    l = line.rstrip('\n')
    names = [(unicodedata.name(c, 'unknown'), ord(c)) for c in l]
    for name, codepoint in names:
        n = name.lower()
        print('{:04x}  {}'.format(codepoint, n), end=eol)
