#! /bin/dash

if daytime ; then
    bg=light
else
    bg=dark
fi

if [ -e "$EXTERNAL_CONDITIONS" ] ; then
    [ "$(cat "$EXTERNAL_CONDITIONS")" = "$bg" ] && exit 1
fi

printf "%s" "$bg" > "$EXTERNAL_CONDITIONS"
togglethm "$bg"
