#! /bin/dash

args=$@
WEATHER_LOCATION=${args:-$WEATHERCODE}
METRIC_URL_SUFFIX="&u=c"

answer=$(wget -qO - "http://xml.weather.yahoo.com/forecastrss?p=${WEATHER_LOCATION}${METRIC_URL_SUFFIX}" | sed -n 's/.*- \([^\.]\+\)\. High: \(-\?[0-9]\+\) Low: \(-\?[0-9]\+\).*/\1 \3 \2/p')

[ -t 1 ] && answer=$(printf "$answer" | sed 's/\(.*\) \(-\?[0-9]\+\) \(-\?[0-9]\+\)/\\033[1;39m\1 \\033[1;34m\2 \\033[1;35m\3\\033[0m/')

if [ -n "$answer" ]; then
    printf "$answer\n"
fi
